GREfun/urls.py
from django.conf.urls import patterns, url
from GREfun import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^about$', views.about, name='about'),
	url(r'^dashboard$', views.dashboard, name="dashboard"),
	url(r'^leaderboard$',views.leaderboard,name='leaderboard'),
	url(r'^logout$',views.logout_view, name="logout"),
	url(r'^wordlist$',views.wordlist, name='wordlist'),
	url(r'^word/(?P<word>\w+)$',views.word_meaning, name='word_meaning'),
	url(r'^question/(?P<question_id>\d+)$', views.question, name='question'),
)

mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^GREfun/',include('GREfun.urls', namespace="GREfun")),
    url(r'^admin/', include(admin.site.urls)),
)

GREfun/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

# Create your models here.
class Word(models.Model):
	word_text = models.CharField(max_length=200)
	def __str__(self):
		return self.word_text 

class Meaning(models.Model):
	meaning_text = models.CharField(max_length=1000)
	word = models.ForeignKey(Word)
	def __str__(self):
		return self.meaning_text+" -> "+self.word.word_text


class Question(models.Model):
	meaning = models.ForeignKey(Meaning)
	choice1 = models.ForeignKey(Word, related_name='question_c1')
	choice2 = models.ForeignKey(Word, related_name='question_c2')
	choice3 = models.ForeignKey(Word, related_name='question_c3')
	points = models.IntegerField(default=1)
	def __str__(self):
		return self.meaning.meaning_text+" :: "+self.choice1.word_text+" :: "+self.choice2.word_text+" :: "+self.choice3.word_text+" :: "+self.meaning.word.word_text+" = "+str(self.points)

class Student(models.Model):
	user = models.OneToOneField(User)
	points = models.IntegerField(default=0)
	questions_total = models.IntegerField(default=0)
	questions_correct = models.IntegerField(default=0)
	def __str__(self):
		return self.user.username

GREfun/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.template import RequestContext, loader
from GREfun.models import Word,Meaning,Question,Student
from random import shuffle
from django.contrib.auth import authenticate,logout, login
from django.contrib.auth.models import User


# Create your views here.
def index(request):
	if request.user.is_authenticated():
		return redirect('/GREfun/dashboard')
	else:
		return render(request, 'GREfun/index.html', {})

def logout_view(request):
	logout(request)
	return redirect('/GREfun')

def about(request):
	return render(request, 'GREfun/about.html', {})

def leaderboard(request):
	all_users = User.objects.all().order_by('student__points')
	return render(request, 'GREfun/leaderboard.html', {"users":all_users})

def dashboard(request):
	print request.user.is_authenticated()
	if request.user.is_authenticated():
		if request.user.student.questions_total == 0:
			ratio = 0
		else:
			ratio = 100*(request.user.student.questions_correct/float(request.user.student.questions_total))
		print ratio
		return render(request, 'GREfun/dashboard.html', {'username': request.user, 'correct_ratio': ratio })
	elif((request.POST.get('username','') != '') and (request.POST.get('password', '') != '')):
		user = authenticate(username=request.POST['username'],password=request.POST['password'])
		print user
		if user is not None:
			login(request,user)
			if user.student.questions_total == 0:
				ratio = 0
			else:
				ratio = 100*(user.student.questions_correct/float(user.student.questions_total))
			return render(request, 'GREfun/dashboard.html', {'user': user, 'correct_ratio': ratio})
		else:
			return HttpResponse("Username/password incorrect.")
	else:
		return redirect('/GREfun')

def wordlist(request):
	meaning_list = Meaning.objects.all()	
	context = {'meaning_list': meaning_list}
	return render(request, 'GREfun/wordlist.html', context)

def word_meaning(request, word):
	meaning_list = Meaning.objects.all()
	try:
		word_ob = Word.objects.get(word_text=word)
	except:
		raise Http404("Word does not exist")
	return render(request, 'GREfun/word_meaning.html', {'word_ob' : word_ob})

def question(request, question_id):
	print 'question: user auth = ' + str(request.user.is_authenticated())
	if not request.user.is_authenticated():
		return HttpResponse("You do not have enough rights to view this page. Please log in.")
	q = get_object_or_404(Question, pk=question_id)
	choices = []
	choices.append(q.meaning.word.word_text)
	choices.append(q.choice1.word_text)
	choices.append(q.choice2.word_text)
	choices.append(q.choice3.word_text)
	shuffle(choices)
	if(request.POST.get('choice',False) != False):
		request.user.student.questions_total += 1
		if(request.POST['choice'] == q.meaning.word.word_text):
			ans = 1
			request.user.student.questions_correct += 1
		else:
			ans = 2
		request.user.student.save()
	else:
		ans = 0
	return render(request, 'GREfun/question.html', {'ans':ans, 'q': q, 'q_prev_id':q.id-1, 'q_next_id':q.id+1, 'choices': choices})

GREfun/templates/GREfun/about.html
{% extends "GREfun/base.html" %}
{% block title %}About{% endblock %}
{% block content %}
<h1>GRE Fun</h1>
<h3>Author: Nishad Dawkhar</h3>
<p>The main goal of this project is to make the study of GRE more fun and less serious. The project aims to integrate multiple social aspects into a student's GRE preparation. A few ideas that come to mind are leaderboards, points, live multiplayer events and timed events. Anything that'll make studying easier and at the same time increase productivity.</p>


<p>Work done:</p>
<ul>
<li>Added basic authentication.</li>
<li>Points for each user with a few additional stats</li>
<li>Leaderboard</li>
<li>Basic Quiz functionality</li>
<li>Word List</li>
<li>Admin page allows addition of words,meanings,questions,users</li>
</ul>
<p>To-do:</p>
<ul>
<li>Get it all working on a nice Bootstrap UI </li>
<li>Polish current features </li>
<li>Create a script that could store 1000s of words,meanings in the Database</li>
<li>Add a concrete and flexible points system</li>
</ul>
{% endblock %}

GREfun/templates/GREfun/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %} GRE Fun {% endblock %}</title>
</head>
<body>
<h1 align="center"><a href="{% url 'GREfun:index' %}">GRE Fun</a></h1>
<p align="center"><a href="{% url 'GREfun:about' %}">About</a></p><br><hr><br><br>
<div id="content">
	{% block content %}{% endblock %}
</div>
<br>
<hr>
<a href="{% url 'GREfun:logout' %}"> Logout </a><br>

GREfun/templates/GREfun/dashboard.html
{% extends "GREfun/base.html" %}
{% block title %}Dashboard{% endblock %}
{% block content %}
<h3><b> User Stats </b></h6>
<p> Name : {{ user.username }} </p>
<p> Questions Attempted : {{ user.student.questions_total }} </p>
<p> Questions Correct : {{ user.student.questions_correct }} </p>
<p> Correct % : {{ correct_ratio }} </p>
<hr><br><br>
<a href="{% url 'GREfun:question' 1 %}"> Attempt Quiz </a><br>
<a href="{% url 'GREfun:wordlist' %}"> Review Words </a><br>
<a href="{% url 'GREfun:leaderboard' %}"> Leaderboard </a>
{% endblock %}

GREfun/templates/GREfun/index.html
{% extends "GREfun/base.html" %}
{% block title %}Gre Fun{% endblock %}

{% block content %}
<form action="{% url 'GREfun:dashboard' %}" method="post">
{% csrf_token %}
<p><b>Username:</b><input type="text" name="username"></p>
<p><b>Password:</b><input type="password" name="password"></p>
<input type="submit" value="Log Me In!"><br><br><hr>
</form>
{% endblock %}

GREfun/templates/GREfun/leaderboard.html
{% extends "GREfun/base.html" %}
{% block title %}Dashboard{% endblock %}
{% block content %}
<ol>
&nbsp;&nbsp;&nbsp;&nbsp; Username&nbsp;&nbsp;&nbsp;&nbsp; Points<hr>
{% for user in users %}
<li> &nbsp;&nbsp;&nbsp;&nbsp; <font color="blue">{{ user.username }}</font>&nbsp;&nbsp;&nbsp;&nbsp; <font color="green">{{ user.student.points }}</font></li>
{% endfor %}
</ol>
{% endblock %}

GREfun/templates/GREfun/logout.html
{% extends "GREfun/base.html" %}
{% block title %}Logout{% endblock %}
{% block content %}
You have been successfully logged out
{% endblock %}

GREfun/templates/GREfun/question.html
{% extends "GREfun/base.html" %}
{% block title %}Gre Fun{% endblock %}

{% block content %}

<h3> {{ q.meaning.meaning_text }} </h1><br><hr><br>
<form action = " {% url 'GREfun:question' q.id %}" method="post">
{% csrf_token %}
{% for choice in choices %}
	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice }}" />
	<label for="choice{{ forloop.counter }}">{{ choice }} </label><br>
{% endfor %}
<br><br>
<input type="submit" value="Submit"><br><br><hr>
</form>
{% if ans == 1 %}
<p><font color="green"> CORRECT </font></p>
{% elif ans == 2 %}
<p><font color="red"> WRONG </font></p>
{% endif %}
<br><br>
<a href="{% url 'GREfun:question' q_next_id %}"> Next Question </a><br>
<a href="{% url 'GREfun:question' q_prev_id %}"> Prev Question </a>
{% endblock %}

GREfun/templates/GREfun/word_meaning.html
word -> {{ word_ob.word_text }} <br><hr>
{% for m in word_ob.meaning_set.all %}
	meaning -> {{ m.meaning_text }}
{% endfor %}

GREfun/templates/GREfun/wordlist.html
{% extends "GREfun/base.html" %}
{% block title %}Gre Fun{% endblock %}

{% block content %}
{% if meaning_list %}
	<ol>
	<font color="red">WORD&nbsp;&nbsp;&nbsp;&nbsp;MEANING</font>
	{% for m in meaning_list %}
		<li><a href="{% url 'GREfun:word_meaning' m.word.word_text %}">{{ m.word.word_text }}</a>&nbsp;&nbsp;&nbsp;&nbsp; {{ m.meaning_text }}</li>
	{% endfor %}
	</ol>
{% else %}
	<p> No words to display </p>
{% endif %}
{% endblock %}